#!/bin/sh
#
# Copyright (c) 2013,The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Changes from Qualcomm Innovation Center, Inc. are provided under the following license:
# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

export MODULE_BASE=/lib/modules/`uname -r`
#To load qcacld driver make MODNAME=wlan
#export MODNAME=wlan

#MODNAME=ath11k_ahb indicates upstream ath11k driver is being loaded
export MODNAME=ath11k_ahb
export RETRY_LIMIT=20
HELP="Usage $0 {start | stop | restart} <ap | sta,ap>"
DUMP_TO_KMSG=/dev/kmsg

model=$(ls /proc/device-tree/soc@0/ | grep "qcom,cnss-" | grep -oP '(?<=qcom,cnss-)[^@]+')
if [ "x$model" = "xqca6490" ]; then
	export MODNAME=$model
fi

do_ctrl_cld_ll () {
    case "$1" in
    start)
        if [ "$MODNAME" != "qca6490" ]; then
                echo "Starting WPSS boot ... $@" > $DUMP_TO_KMSG
                echo 1 > /sys/kernel/icnss/wpss_boot
        fi

        echo "Starting WLAN... $@" > $DUMP_TO_KMSG

        if [ "$MODNAME" = "qca6490" ]; then
                echo 1 > /sys/bus/pci/rescan
        fi

        modprobe $MODNAME

        c=1
        ifconfig wlan0 up 2>  /dev/null
        rc=$?
        while [ $rc -ne 0 -a $c -le $RETRY_LIMIT ]; do
            sleep 1
            ifconfig wlan0 up 2> /dev/null
            rc=$?
            c=`expr $c + 1`
        done

        if [ $c -gt $RETRY_LIMIT ]; then
            echo "WLAN bring-up failed!" > $DUMP_TO_KMSG
            exit 1
        fi

        echo "Set Wake On Wireless Pattern ... $@" > $DUMP_TO_KMSG
        iw phy0 wowlan enable magic-packet
        ;;

    stop)
        echo "Stopping WLAN..." > $DUMP_TO_KMSG
        if [ "$MODNAME" = "wlan" ]; then
            rmmod $MODNAME
        fi
        ;;

    restart)
        do_ctrl_cld_ll stop
        shift
        do_ctrl_cld_ll start $@

        return $?
        ;;

    *)
        return 1
        ;;
    esac

    return 0
}

do_ctrl_cld_ll $@
if [ $? -ne 0 ]; then
    echo $HELP >&2
    exit 1
fi

exit 0
