# Only WPA-PSK is used. Any valid cipher combination is accepted.
ctrl_interface=/var/run/sockets
update_config=1
wowlan_triggers=magic_pkt

network={
#Open-Configuration
#        ssid="example open network"
#        key_mgmt=NONE
#WPA-PSK-configuration
#Update the SSID to match that of the Wi-Fi SSID of your router.
#	ssid="QSoftAP"
#	proto=WPA RSN
#	key_mgmt=WPA-PSK
#	pairwise=TKIP CCMP
#	group=TKIP CCMP
# Update the password to match that of the Wi-Fi password of your router.
#	psk="1234567890"
#WEP-configuration
#	ssid="example wep network"
#	key_mgmt=NONE
#	wep_key0="abcde"
#	wep_key1=0102030405
#	wep_tx_keyidx=0
}
