##### hostapd configuration file ####################

interface=wlan0
driver=nl80211
logger_syslog=-1
logger_syslog_level=2
logger_stdout=-1
logger_stdout_level=2
ctrl_interface=/var/run/hostapd
ssid=QCS6490_SoftAP
hw_mode=g
channel=6
beacon_int=100
dtim_period=2
ieee80211n=1
ieee80211ax=1
wpa=2
wpa_passphrase=123456789
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
