#!/bin/sh
# Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

export MODULE_BASE=/lib/modules/`uname -r`
export RETRY_LIMIT=15
HELP="Usage $0 {start | stop | restart} <ap | sta,ap>"
DUMP_TO_KMSG=/dev/kmsg
MODNAME=wlan
INIPATH=/lib/firmware/wlan/qca_cld

do_ctrl_cld_ll () {
    case "$1" in
    start)
        echo "Starting WLAN... $@" > $DUMP_TO_KMSG
        shift
        start_ap1=0
        if [ "$1" == "ap,ap" ] || [ "$1" == "sta,ap" ]; then
            start_ap1=1
            shift
        elif [ "$1" == "ap" ]; then
            shift
        elif [ "$1" == "ap,sta" ]; then
            return 1
        fi

        model=$(cat /proc/device-tree/model | grep -a "IoT RB3 GEN2")
        if [ "$model" != "" ]; then
            MODNAME=wlan-msl
            if [ ! -f $INIPATH/$MODNAME/WCNSS_qcom_cfg.ini ]; then
                ln -s $INIPATH/WCNSS_qcom_cfg.ini.msl $INIPATH/$MODNAME/WCNSS_qcom_cfg.ini
            fi
            echo "Write 1 to Wpss_boot $@" > $DUMP_TO_KMSG
            echo 1 > /sys/devices/platform/soc/17a10040.qcom,wcn6750/wpss_boot
        else
            echo "Write WLAN fs_ready $@" > $DUMP_TO_KMSG
            echo 1 > /sys/devices/platform/soc/b0000000.qcom,cnss-qca6490/fs_ready
        fi
        set -e
        insmod $MODULE_BASE/extra/$MODNAME.ko $@
        set +e

        c=1
        ifconfig wlan0 up 2>  /dev/null
        rc=$?
        while [ $rc -ne 0 -a $c -le $RETRY_LIMIT ]; do
            sleep 1
            ifconfig wlan0 up 2> /dev/null
            rc=$?
            c=`expr $c + 1`
        done

        if [ $c -gt $RETRY_LIMIT ]; then
            echo "WLAN bring-up failed!" > $DUMP_TO_KMSG
            exit 1
        fi

        /usr/sbin/wpa_supplicant -Dnl80211 -iwlan0 -c /etc/wlan/wpa_supplicant.conf &

        if [ $start_ap1 -eq 1 ]; then
            echo "Adding second AP interface(wlan1)" > $DUMP_TO_KMSG
            iw dev wlan0 interface add wlan1 type __ap
            ifconfig wlan1 up 2> /dev/null
        fi
        ;;

    start_ftm)
        do_ctrl_cld_ll start con_mode=5
        ;;

    stop)
        echo "Stopping WLAN..." > $DUMP_TO_KMSG
        rmmod $MODNAME
        ;;

    restart)
        do_ctrl_cld_ll stop
        shift
        do_ctrl_cld_ll start $@

        return $?
        ;;

    *)
        return 1
        ;;
    esac

    return 0
}

do_ctrl_cld_ll $@
if [ $? -ne 0 ]; then
    echo $HELP >&2
    exit 1
fi

exit 0
