#!/bin/sh
#
# Copyright (c) 2019, 2021, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# cnss module init.d script

export MODULE_BASE=/lib/modules/`uname -r`/
set -e

case "$1" in
  start)
        if [ "$(ls -A "/sys/devices/platform" | grep qcom,cnss-qca)" ];
        then
                echo -n "Loading cnss platform driver: "
        else
                echo -n "No MCC chip"
                exit 0
        fi

        # Set board_name to be used
        if [ "$(cat /sys/firmware/devicetree/base/model | grep -c "SDXLEMUR")" ];
        then
                mkdir -p /tmp/sysinfo/
                echo "ap-sdxlemur-65" > /tmp/sysinfo/board_name
        else
                echo "WLAN driver not supported" > /dev/kmsg
                exit 0
        fi

        mkdir -p /systemrw/wlan/bin/
        ln -sf /usr/sbin/mcc/* /systemrw/wlan/bin/

        mkdir -p /systemrw/wlan/config/
        if [ -f /etc/misc/wifi/2g_wireless ]; then
                ln -sf /etc/misc/wifi/2g_wireless /systemrw/wlan/config/2g_wireless
        fi
        if [ -f /etc/misc/wifi/5g_wireless ]; then
                ln -sf /etc/misc/wifi/5g_wireless /systemrw/wlan/config/5g_wireless
        fi

        ln -sf /usr/sbin/ipq/pairing_client_app /systemrw/wlan/bin/pairing_client_app
        ln -sf /usr/sbin/ipq/provisioning_test_app /systemrw/wlan/bin/provisioning_test_app
        ln -sf /usr/sbin/ipq/encrypt_client_app /systemrw/wlan/bin/encrypt_client_app
        ln -sf /usr/bin/ipq/afc /systemrw/wlan/bin/afc

        if [ -f $MODULE_BASE/kernel/drivers/net/wireless/cnss2/cnss2.ko ];
        then
                echo "Load cnss platform drivers " > /dev/kmsg
                insmod $MODULE_BASE/kernel/drivers/net/wireless/cnss_utils/wlan_firmware_service_v01.ko
                insmod $MODULE_BASE/kernel/drivers/net/wireless/cnss_utils/device_management_service_v01.ko
                insmod $MODULE_BASE/kernel/drivers/net/wireless/cnss2/cnss2.ko
        else
                echo "cnss module does not exist "
        fi

        echo "Done loading cnss platform driver "

        wlan_cfg="/etc/data/wlan_cfg.xml"
        mobileap_cfg="/etc/data/mobileap_cfg.xml"
        if [ ! -f $wlan_cfg ] || [ ! -f $mobileap_cfg ]; then
		        echo "$wlan_cfg or $mobileap_cfg not exist" > /dev/kmsg
		        exit 0
        fi
        EZMeshEnabled=`grep EZMeshEnable $wlan_cfg | awk -F ">" '{print $2}' | awk -F "<" '{print $1}'`
        WLANEnableAtBootup=`grep WLANEnableAtBootup $mobileap_cfg | awk -F ">" '{print $2}' | awk -F "<" '{print $1}'`
        echo "EZMeshEnabled=$EZMeshEnabled, WLANEnableAtBootup=$WLANEnableAtBootup" > /dev/kmsg
        if [ $EZMeshEnabled == 1 ] && [ $WLANEnableAtBootup == 1 ]; then
                echo "start to mount ezmesh files" > /dev/kmsg
                /sbin/mount-copybind /systemrw/ipq/config/wireless /etc/config/wireless
                /sbin/mount-copybind /systemrw/ipq/config/ezmesh /etc/config/ezmesh
                /sbin/mount-copybind /systemrw/ipq/config/wsplcd /etc/config/wsplcd
                /sbin/mount-copybind /systemrw/ipq/config/repacd /etc/config/repacd
                /sbin/mount-copybind /systemrw/ipq/config/ezlbd /etc/config/ezlbd
                /sbin/mount-copybind /systemrw/ipq/config/bss-policy.conf /etc/wsplcd/map/bss-policy.conf
                /sbin/mount-copybind /systemrw/ipq/config/map.conf /etc/config/map.conf
                /sbin/mount-copybind /systemrw/ipq/config/scheme-a.conf /etc/wsplcd/map/templates/scheme-a.conf
                /sbin/mount-copybind /systemrw/ipq/config/scheme-b.conf /etc/wsplcd/map/templates/scheme-b.conf
                /sbin/mount-copybind /systemrw/ipq/config/scheme-c.conf /etc/wsplcd/map/templates/scheme-c.conf
                /sbin/mount-copybind /systemrw/ipq/config/scheme-d.conf /etc/wsplcd/map/templates/scheme-d.conf
                /sbin/mount-copybind /systemrw/ipq/config/scheme-e.conf /etc/wsplcd/map/templates/scheme-e.conf
                /sbin/mount-copybind /systemrw/ipq/config/sp-rules.conf /etc/ezmesh/sp-rules.conf
                echo "mount ezmesh files done" >/dev/kmsg
        fi
        ;;
  stop)
        echo -n "Unloading cnss platform driver "
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
