#!/bin/sh
#
# Copyright (c) 2019, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# cnss module init.d script

export MODULE_BASE=/lib/modules/`uname -r`/
set -e

case "$1" in
  start)
	if [ $(cat /sys/firmware/devicetree/base/model | grep -c ROME) = 1 ];then
		echo -n "cnss: Rome device " > /dev/kmsg
		if [ -f $MODULE_BASE/kernel/drivers/net/wireless/cnss/cnss.ko ];
		then
			echo "Load cnss platform driver " > /dev/kmsg
			insmod $MODULE_BASE/kernel/drivers/net/wireless/cnss/cnss.ko
			insmod $MODULE_BASE/kernel/drivers/net/wireless/cnss/logger/logger.ko
		else
			echo "cnss module does not exist "
		fi
		/sbin/mount-copybind /systemrw/misc/wifi/WCNSS_qcom_cfg.ini /etc/misc/wifi/WCNSS_qcom_cfg.ini
		/sbin/mount-copybind /systemrw/misc/wifi/WCNSS_qcom_cfg.Rome.ini /etc/misc/wifi/WCNSS_qcom_cfg.Rome.ini
		if [ ! -f /systemrw/misc/wifi/WCNSS_qcom_cfg.hsp.ini ]; then
			cp /systemrw/misc/wifi/WCNSS_qcom_cfg.ini /systemrw/misc/wifi/WCNSS_qcom_cfg.hsp.ini
			cp /etc/misc/wifi/WCNSS_qcom_cfg.Rome.ini /etc/misc/wifi/WCNSS_qcom_cfg.ini
		fi
	else
		if [ -f $MODULE_BASE/kernel/drivers/net/wireless/cnss2/cnss2.ko ];
		then
			echo "Load cnss platform driver " > /dev/kmsg
			insmod $MODULE_BASE/kernel/drivers/net/wireless/cnss2/cnss2.ko
		else
			echo "cnss module does not exist "
		fi
	fi
         echo "Done loading cnss platform driver "
        ;;
  stop)
        echo -n "Unloading cnss platform driver "
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
