# This file allows user to override the factory
# defaults for the WLAN Driver

gDot11Mode=0
InfraUapsdVoSrvIntv=0
InfraUapsdViSrvIntv=0
InfraUapsdBeSrvIntv=0
InfraUapsdBkSrvIntv=0
gAddTSWhenACMIsOff=1
gEnableApOBSSProt=1
RTSThreshold=1048576
g11dSupportEnabled=0
gEnableDFSMasterCap=1
gNeighborScanTimerPeriod=200
gNeighborLookupThreshold=76
FastRoamEnabled=1
RoamRssiDiff=5
gChannelBondingMode5GHz=1
gAllowDFSChannelRoam=1
gSetTxChainmask1x1=1
gSetRxChainmask1x1=1
gWlanMccToSccSwitchMode = 3
gEnableTXSTBC=1
gEnableTxBFeeSAP=1
gEnableTxBFin20MHz=1
gEnableTxSUBeamformer=1
gRrmEnable=1
gVhtAmpduLenExponent=7
gVhtMpduLen=2
isP2pDeviceAddrAdministrated=0
gEnableVhtFor24GHzBand=1
gEnableLpassSupport=1
gCountryCodePriority=1
gEnableMuBformee=1
gTDLSExternalControl=1
gEnableTDLSOffChannel=1
gNumVdevs=5
gSoftApMaxPeers=64

################ Datapath feature set Begin ################
gVhtRxMCS=2
gVhtTxMCS=2
gEnable2x2=1
gVhtRxMCS2x2=2
gVhtTxMCS2x2=2
gIPAConfig=0x46d
gIPADescSize=800
rx_mode=20
gEnableFastPath=1
TSOEnable=1
GROEnable=1
ght_mpdu_density=5
gEnableFlowSteering=1
maxMSDUsPerRxInd=8
gEnableNUDTracking=1
dp_rx_fisa_enable=1
dp_rx_flow_search_table_size=256
dp_rx_fst_in_cmem=1
dp_rx_fisa_lru_del_enable=1
dp_reo_dest_rings=4
dp_rx_refill_buff_pool=1
rpsRxQueueCpuMapList=f3
legacy_mode_csum_disable=1
icmp_req_to_fw_mark_interval=200
gBusBandwidthVeryHighThreshold=10000

gRxAggregationSize=1024
tx_pkt_inspect_for_ilp=0
################ Datapath feature set End ################

adaptive_dwell_mode_enabled=1
hostscan_adaptive_dwell_mode=1
enable_rtt_mac_randomization=1
gEnableSNRMonitoring=1
gWmiCreditCount=1
acs_with_more_param=1
AutoChannelSelectWeight=0x0ffafafa
gRuntimePM=2
gRuntimePMDelay=500
gEnablePacketLog=0
oem_6g_support_disable=0

active_max_channel_time_2g=80
gActiveMaxChannelTime=60
active_max_channel_time_6g=60
passive_max_channel_time_6g=60
gMaxConcurrentActiveSessions=4

dp_tx_desc=256
dp_tx_ext_desc=256
dp_tx_compl_ring_size=256

dp_rxdma_refill_ring=3072
dp_reo_dst_ring=1024

dp_ipa_tx_comp_ring_size=512
dp_ipa_tx_ring_size=512
dp_ipa_tx_alt_comp_ring_size=512
dp_ipa_tx_alt_ring_size=512

dp_max_clients=16

#Flag to enable HostNSOffload feature or not
hostNSOffload=0

#Flag to enable NLO/PNO feature or not
gPNOScanSupport=0

#Flag to disable SAP/GO D3WoW feature
enable_bus_suspend_in_sap_mode=0
enable_bus_suspend_in_go_mode=0

#Flag to disable SSDP
ssdp=0

twt_congestion_timeout=0

# Bit map for enabling the SRD mode in various modes are as follows:-
# BIT 0:- Enable/Disable SRD channels for SAP.
# BIT 1:- Enable/Disable SRD channels for P2P-GO.
# BIT 2:- Enable/Disable SRD channels for NAN.
etsi13_srd_chan_in_master_mode=1

cfr_disable=1
spectral_disable=1
he_max_ampdu_len=1

# IPA perf level force voting
gIPAForceVotingEnable=1

# IPA perf level on sdxpinn
# 4800 - NOMINAL
# 1400 - SVS
# 800 - Low-SVS
gIPAHighBandwidthMbps=4800
gIPAMediumBandwidthMbps=1400
gIPALowBandwidthMbps=800

END

# Note: Configuration parser would not read anything past the END marker

