# Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear
ctrl_interface=/var/run/wpa_supplicant
disable_scan_offload=1
update_config=1
# You can use P2P_GO P2P_Client P2P_A P2P_B or whatever you want
device_name=P2P
device_type=10-0050F204-5
config_methods=display push_button keypad virtual_push_button physical_display
persistent_reconnect=1
p2p_group_idle=1000000
p2p_add_cli_chan=1
p2p_optimize_listen_chan=1
p2p_go_ht40=1
p2p_go_vht=1
p2p_go_he=1
p2p_no_group_iface=1
bss_max_count=400
pmf=1
sae_pwe=2
p2p_device_persistent_mac_addr=da:85:83:88:88:88
