#Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear
# Enable GPIO wakeup for WoW
genable_gpio_wakeup=1
# 2:indicates failing trigger
ggpio_wakeup_mode=2
# imx8mqevk's GPIO5_11
ggpio_wakeup_pin=139
