#!/bin/sh
#
# Copyright (c) 2013, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#
# Changes from Qualcomm Technologies, Inc. are provided under the following license:
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries. 
# SPDX-License-Identifier: BSD-3-Clause-Clear

export MODULE_BASE=/lib/modules/`uname -r`
export RETRY_LIMIT=10
HELP="Usage $0 {init-start | start | stop | restart} <ap | sta,ap>"
DUMP_TO_KMSG=/dev/kmsg
MODNAME=wlan
IFNAME=wlan

do_ctrl_cld_ll () {
    case "$1" in
    init-start)
        #checking WLAN chip ID
        chip_id=$(lspci -n | grep "17cb:1112")
        if [ -n "$chip_id" ]; then
            echo "Detected wcn7760 chip" > $DUMP_TO_KMSG
            MODNAME=qca_cld3_wcn7760
            echo 1 > /sys/kernel/cnss/fs_ready
            sleep 1
        else
            echo "Starting WLAN Calibration..." > $DUMP_TO_KMSG
            echo 1 > /sys/kernel/icnss/wpss_boot
        fi

        res='ls $MODULE_BASE/ | grep ${MODNAME}.ko'
        mod=$(eval "$res")
        if [ $mod == "${MODNAME}.ko" ]; then
            MODNAME=${MODNAME}
        else
            echo "WLAN Module Not Found!" > $DUMP_TO_KMSG
            exit 1
        fi

        set -e
        insmod $MODULE_BASE/${MODNAME}.ko
        set +e
        ;;

    start)
        echo "Starting WLAN... $@" > $DUMP_TO_KMSG
        do_ctrl_cld_ll init-start
        shift
        start_ap1=0
        if [ "$1" == "ap,ap" ] || [ "$1" == "sta,ap" ]; then
            start_ap1=1
            shift
        elif [ "$1" == "ap" ]; then
            shift
        elif [ "$1" == "ap,sta" ]; then
            return 1
        fi

        c=1
        ifconfig ${IFNAME}0 up 2>  /dev/null
        rc=$?
        while [ $rc -ne 0 -a $c -le $RETRY_LIMIT ]; do
            sleep 1
            ifconfig ${IFNAME}0 up 2> /dev/null
            rc=$?
            c=`expr $c + 1`
        done

        if [ $c -gt $RETRY_LIMIT ]; then
            echo "WLAN bring-up failed!" > $DUMP_TO_KMSG
            exit 1
        fi

        if [ $start_ap1 -eq 1 ]; then
            echo "Adding second AP interface(${IFNAME}1)" > $DUMP_TO_KMSG
            iw dev ${IFNAME}0 interface add ${IFNAME}1 type __ap
            ifconfig ${IFNAME}1 up 2> /dev/null
        fi
        ;;

    start_ftm)
        do_ctrl_cld_ll stop
        do_ctrl_cld_ll start
        echo 5 > /sys/module/wlan/parameters/con_mode
        ;;

    stop)
        echo "Stopping WLAN..." > $DUMP_TO_KMSG
        killall hostapd
        killall wpa_supplicant
        res='ls $MODULE_BASE/ | grep ${MODNAME}.ko'
        mod=$(eval "$res")
        if [ $mod == "${MODNAME}.ko" ]; then
            MODNAME=${MODNAME}
            shift
        else
            MODNAME=${MODNAME}_debug
        fi

        rmmod ${MODNAME}
        ;;

    restart)
        do_ctrl_cld_ll stop
        shift
        do_ctrl_cld_ll start $@

        return $?
        ;;

    *)
        return 1
        ;;
    esac

    return 0
}

do_ctrl_cld_ll $@
if [ $? -ne 0 ]; then
    echo $HELP >&2
    exit 1
fi

exit 0
